/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */
// This file is auto-generated by the build script (scripts/generate-git-commit-info.js)
// Do not edit this file manually.
export const GIT_COMMIT_INFO = 'c1c6a6d63';
export const CLI_VERSION = '0.8.0-nightly.20250925.b1da8c21';
//# sourceMappingURL=git-commit.js.map